version: "3.9"
services:
  ################################ MINIO #######################################
  minio:
    image: minio/minio:latest
    command: server /files --console-address :9001
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: accessKey
      MINIO_ROOT_PASSWORD: secretAccessKey
    volumes:
      - minio:/files

  ############################### storage-service ########################
  storage-service:
    image: java-object-storage
    ports:
      - "5555:5555"
    environment:
      MINIO_URL: http://minio:9000
    depends_on:
      - minio

volumes:
  minio:
